version: '3.9'
services:
  postgres:
    image: postgres:alpine
    ports:
      - '5432:5432'
    container_name: 'postgres'
    restart: always  
    volumes:
      - .docker/dbdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

  app:
      build:
        context: .
        dockerfile: Dockerfile
      container_name: 'bank-api'    
      restart: always  
      volumes:
        - .:/app  
        - /app/node_modules
      env_file: ./.env      
      environment:
        DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/postgres?schema=public"                     
      ports:
        - 3000:3000
      depends_on:
        - postgres
      command: >
        sh -c "
        until nc -z postgres 5432;
        do
          echo waiting for postgres;
          sleep 2;
        done;
        npx prisma migrate deploy && npm run start:dev"

