version: '3.9'
services:
  postgres_test:
    image: postgres:alpine
    ports:
      - '5433:5432'
    container_name: 'postgres_test'
    volumes:
      - .docker/dbdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres_test
